"use client";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import type { RootState } from "@/GlobalRedux/store";
import { useSelector, useDispatch } from "react-redux";
import { increment } from "../GlobalRedux/Features/Counter/counterSlice";
import { useRouter } from "next/router";
import {LandingNav, 
  HeroSection,
   LandingThreeGrid,
   OurServices,
    WhyChooseUs,
     LandingThreeSecond,
     LandingContact,
     LandingFooter,
     
    
    } from "../Components/components";


export default function Home() {
  const count = useSelector((state: RootState) => state.counter.value);
  const dispatch = useDispatch();
  const router = useRouter();

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className="hidden lg:block h-fit gap-y-10">
        <LandingNav/>
        <HeroSection/>
        <LandingThreeGrid/>
        <OurServices/>
        <WhyChooseUs/>
        <LandingThreeSecond/>
        <LandingContact/>
        <LandingFooter/>

      </main>
      <div className="lg:hidden text-2xl">
        Not For MOBILE SCREENS , Please Check on Laptop or Desktop
      </div>
    </>
  );
}
